---
# handlers file for financio-installer/
- name: Restart ssh
  service: name=ssh state=restarted

- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata
 
- name: start Mysql service
  service: name=mysql state=started 

- name: restart apache2 service
  service: name=apache2 state=restarted

- name: restart postfix
  service: name=postfix state=restarted
